---
pipeline:
  projectIdentifier: "jmantillabootcamp"
  orgIdentifier: "default"
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: "Githubjlm"
        build: "<+input>"
  stages:
  - stage:
      name: "clone"
      identifier: "clone"
      type: "CI"
      spec:
        cloneCodebase: true
        execution:
          steps:
          - step:
              type: "Run"
              name: "Build"
              identifier: "Run_1"
              spec:
                connectorRef: "account.bootcampdockerhub"
                image: "nikpap/mvn-openjdk-8:harness"
                shell: "Sh"
                command: "cd payment-service\nmvn -Dmaven.test.skip=true clean install\
                  \ -X"
                resources:
                  limits:
                    memory: "1Gi"
                    cpu: "1"
          - step:
              type: "BuildAndPushDockerRegistry"
              name: "Build and Push an image to Docker Registry_1"
              identifier: "BuildandPushanimagetoDockerRegistry_1"
              spec:
                connectorRef: "Dockerhub"
                repo: "joseluismantilla/harness"
                tags:
                - "1.0"
                - "latest"
                dockerfile: "/harness/payment-service/Dockerfile"
                optimize: false
                resources:
                  limits:
                    memory: "1Gi"
                    cpu: "1"
              failureStrategies: []
        infrastructure:
          type: "KubernetesDirect"
          spec:
            connectorRef: "account.bootcampgkecluster"
            namespace: "payment-service"
            automountServiceAccountToken: true
            nodeSelector: {}
            os: "Linux"
  identifier: "githubharness_http"
  name: "github-harness - http"
