pipeline:
  name: Pipeline-demo
  identifier: Pipelinedemo
  projectIdentifier: jmantillabootcamp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Githubjlm
        build: <+input>
  stages:
    - stage:
        name: clone
        identifier: clone
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: RunTests
                  name: Tests
                  identifier: Tests
                  spec:
                    connectorRef: Dockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    language: Java
                    buildTool: Maven
                    args: test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: Dockerhub
                    image: nikpap/mvn-openjdk-8:harness
                    shell: Sh
                    command: |-
                      cd payment-service
                      mvn -Dmaven.test.skip=true clean install -X
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push an image to Docker Registry_1
                  identifier: BuildandPushanimagetoDockerRegistry_1
                  spec:
                    connectorRef: Dockerhub
                    repo: joseluismantilla/harness
                    tags:
                      - "1.0"
                      - latest
                    dockerfile: /harness/payment-service/Dockerfile
                  failureStrategies: []
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.bootcampgkecluster
              namespace: payment-service
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
