pipeline:
  name: Pipeline-demo
  identifier: Pipelinedemo
  projectIdentifier: jmantillabootcamp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Githubjlm
        build: <+input>
  stages:
    - stage:
        name: clone
        identifier: clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push an image to Docker Registry_1
                  identifier: BuildandPushanimagetoDockerRegistry_1
                  spec:
                    connectorRef: Dockerhub
                    repo: joseluismantilla/harness
                    tags:
                      - v1.0
                    dockerfile: payment-service/Dockerfile
                  failureStrategies: []
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: Dockerhub
                    image: ubuntu
                    shell: Sh
                    command: echo "Hello World"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.bootcampgkecluster
              namespace: payment-service
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
